# Generated by Django 2.1.2 on 2018-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafit', '0003_load_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related',
            field=models.ManyToManyField(related_name='_article_related_+', to='grafit.Article'),
        ),
    ]
