# Generated by Django 2.1.2 on 2018-10-25 09:36

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grafit', '0005_auto_20181029_1255'),
    ]

    operations = [
        migrations.RunSQL("""
            BEGIN;
            SELECT setval(pg_get_serial_sequence('"grafit_article_related"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "grafit_article_related";
            SELECT setval(pg_get_serial_sequence('"grafit_article"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "grafit_article";
            COMMIT;
        """),
    ]
