# Generated by Django 2.1.3 on 2018-11-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafit', '0010_fix_ids2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='related',
        ),
    ]
