# Generated by Django 2.1.3 on 2018-11-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafit', '0012_create_search_index'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS grafit_search_unique;
            
            CREATE UNIQUE INDEX grafit_search_unique
            ON grafit_search_index (id);
            """
        ),
    ]
