# Generated by Django 2.1.3 on 2018-12-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafit', '0013_add_unique_to_searchindex'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE EXTENSION IF NOT EXISTS pg_trgm;
            DROP MATERIALIZED VIEW IF EXISTS grafit_search_word;

            CREATE MATERIALIZED VIEW grafit_search_word AS
                SELECT *
                FROM ts_stat(
                    'SELECT to_tsvector(''english'', node.title) ||
                    to_tsvector(''english'',coalesce(node.text, ''''))
                    FROM grafit_article as node'
                );

            CREATE INDEX words_idx ON grafit_search_word USING gin(word gin_trgm_ops);

            DROP INDEX IF EXISTS grafit_search_word_unique;
            CREATE UNIQUE INDEX grafit_search_word_unique ON grafit_search_word (word);
            """
        )
    ]
