# Generated by Django 2.1.3 on 2018-12-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafit', '0014_create_search_word_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('headline', models.TextField()),
                ('rank', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'search_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('word', models.TextField(primary_key=True, serialize=False)),
                ('similarity', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'search_word',
                'managed': False,
            },
        ),
    ]
